apiVersion: v1alpha
kind: cypress
sauce:
  concurrency: 4
  region: us-west-1
  metadata:
    name: Testing Cypress Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
npm:
  registry: https://registry.npmjs.org
  packages:
    cypress: "^4.8.0"
    cypress-log-to-output: "^1.1.2"
    cypress-testrail-reporter: "^1.2.8"
    mochawesome: "^6.2.2"
    mochawesome-merge: "^4.2.0" 
cypress:
  version: 7.1.0
  configFile: "cypress.json"  # We determine related files based on the location of the config file.
suites:
  - name: "Tabula_Rasa_POC_TC#1"
    browser: "chrome"
    platformName: "Windows 10"
    config:
      testFiles: ['**/ondemand_poc.js']
  # - name: "Tabula_Rasa_POC_TC#2"
  #   browser: "chrome"
  #   platformName: "Windows 10"
  #   config:
  #     testFiles: ['**/vaccinations_poc.js']
  # - name: "Tabula_Rasa_POC_TC#3"
  #   browser: "chrome"
  #   platformName: "Windows 10"
  #   config:
  #     testFiles: ['**/ecare_poc.js']
  # - name: "Tabula_Rasa_POC_TC#4"
  #   browser: "chrome"
  #   platformName: "Windows 10"
  #   config:
  #     testFiles: ['**/NegativeScenario_ReTry.js']   
  # - name: "Tabula_Rasa_POC_TC#6-Vaccinations-MicrosoftEdge"
  #   browser: "microsoftedge"
  #   platformName: "Windows 10"
  #   config:
  #     testFiles: ['**/vaccinations_poc.js']        
# artifacts:
#   download:
#     when: always
#     match:
#       - console.log
#     directory: ./artifacts/        